app/data/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from app.models import *
from app import db
from sqlalchemy import func, inspect

data = Blueprint('data', __name__)

@data.route('/data/hrdp')
def data_hrdp():

    tableset = {}
    columnset = {}

    # strain
    # data list
    strains = Strain.query.all()
    # column list
    strain_columns = Strain.metadata.tables['Strain'].columns.keys()

    tableset['strain'] = strains
    columnset['strain'] = strain_columns

    # animal
    # data list
    animals = Animal.query.all()
    # column list
    animal_columns = Animal.metadata.tables['Animal'].columns.keys()

    tableset['animal'] = animals
    columnset['animal'] = animal_columns

    # tissue
    # data list
    tissues = Tissue.query.all()
    # column list
    tissue_columns = Tissue.metadata.tables['Tissue'].columns.keys()

    tableset['tissue'] = tissues
    columnset['tissue'] = tissue_columns

    # sequencing
    # data list
    sequencing_columns = Sequencing.metadata.tables['Sequencing'].columns.keys()
    sequencings = Sequencing.query.all()

    tableset['sequencing'] = sequencings
    columnset['sequencing'] = sequencing_columns

    # analysis
    # data list
    analyses = Analysis.query.all()
    # column list
    analysis_columns = Analysis.metadata.tables['Analysis'].columns.keys()

    tableset['analysis'] = analyses
    columnset['analysis'] = analysis_columns

    return render_template('data_hrdp.html', title='HRDP', tableset=tableset, columnset=columnset)

@data.route('/')
@data.route('/view')
def view():
    # sequencing
    # data list
    view_list = db.session.query(
        Sequencing.Run_ID.label("RunID"),
        Animal.Strain_name.label("Rat_Strain"),
        Tissue.Type.label("Tissue_name"),
        Sequencing.Platform.label("Platform")).join(Tissue).join(Animal, Tissue.Animal_ID == Animal.Animal_name).all()

    view_column_list = ['RunID', 'Rat_Strain', 'Tissue_name', 'Platform']

    return render_template('view.html', title='Sequencing View', columnset=view_column_list, tableset=view_list)

@data.route("/data/view_detail/<string:run_id>")
def view_detail(run_id):

    tableset = {}
    columnset = {}

    column_list = ['Strain', 'Animal','Tissue','Sequencing','Analysis','LongRanger results','Deepvariant results','Supernova results' ]

    # collecting columns for each table
    strain_columns = Strain.metadata.tables['Strain'].columns.keys()
    animal_columns = Animal.metadata.tables['Animal'].columns.keys()
    tissue_columns = Tissue.metadata.tables['Tissue'].columns.keys()
    sequencing_columns = Sequencing.metadata.tables['Sequencing'].columns.keys()
    analysis_columns = Analysis.metadata.tables['Analysis'].columns.keys()
    deepvariant_results_columns = Deepvariant_results.metadata.tables['Deepvariant_results'].columns.keys()
    longRanger_results_columns = LongRanger_results.metadata.tables['LongRanger_results'].columns.keys()
    supernova_results_columns = Supernova_results.metadata.tables['Supernova_results'].columns.keys()

    # collecting data from each table
    # sequencing
    sequencings = Sequencing.query.filter(Sequencing.Run_ID == run_id).first()

    # tissue
    tissue_id = getattr(sequencings, 'DNA_source')
    tissues = Tissue.query.filter(Tissue.ID == tissue_id).first()

    # animal
    animal_name = getattr(tissues, 'Animal_ID')
    animals = Animal.query.filter(Animal.Animal_name == animal_name).first()

    # strain
    strain_name = getattr(animals, 'Strain_name')
    strains = Strain.query.filter(Strain.Name == strain_name).first()

    # analysis
    analyses = Analysis.query.filter(Analysis.Sequencing_ID == run_id).all()
   
   
   # TODO must be fixed with this part
    Deepvariant_res = None
    LongRanger_res = None
    Supernova_res = None
    for analysis in analyses:
        deepvariant_result = Deepvariant_results.query.filter(Deepvariant_results.Analysis_ID == getattr(analysis, 'Analysis_ID')).all()
        longRanger_result = LongRanger_results.query.filter(LongRanger_results.Analysis_ID == getattr(analysis, 'Analysis_ID')).first()
        supernova_result = Supernova_results.query.filter(Supernova_results.Analysis_ID == getattr(analysis, 'Analysis_ID')).first()    
        
        if deepvariant_result !=None:
            Deepvariant_res = deepvariant_result

        if longRanger_result !=None:
            LongRanger_res = longRanger_result    
        
        if supernova_result !=None:
            Supernova_res = supernova_result

    # tableset setting
    tableset['Sequencing'] = sequencings
    tableset['Tissue'] = tissues
    tableset['Animal'] = animals
    tableset['Strain'] = strains
    tableset['Analysis'] = analyses
    tableset['Deepvariant results'] = Deepvariant_res
    tableset['LongRanger results'] = LongRanger_res
    tableset['Supernova results'] = Supernova_res


    # columnset filtering
    columnset['Analysis'] = analysis_columns.remove('Sequencing_ID')
    columnset['Sequencing'] = sequencing_columns.remove('Run_ID')
    columnset['Tissue'] = tissue_columns.remove('Animal_ID')
    columnset['Animal'] = animal_columns.remove('Strain_name')

    # columnset setting
    columnset['Sequencing'] = sequencing_columns
    columnset['Tissue'] = tissue_columns
    columnset['Animal'] = animal_columns
    columnset['Strain'] = strain_columns
    columnset['Analysis'] = analysis_columns
    if Deepvariant_res != None:
        columnset['Deepvariant results'] = deepvariant_results_columns
    if LongRanger_res != None:
        columnset['LongRanger results'] = longRanger_results_columns
    if Supernova_res != None:
        columnset['Supernova results'] = supernova_results_columns

    return render_template('view_detail.html', title='Sequencing Data', tableset=tableset, columnset=columnset,column_list=column_list, detail_target=run_id)

app/visuals/routes.py
from flask import Blueprint
from flask import render_template, url_for, flash, redirect, request, Blueprint
from app.models import User, Post, CVocab, Strain, Animal, Tissue, Sequencing, Analysis
from app import db
from app import mysql


visuals = Blueprint('visuals', __name__)

@visuals.route('/wli/dels')
def gwlidel():
    data = []

    cur = mysql.connection.cursor()
    cur.execute("select CONCAT(\"GGG_\", CHROM), starting_position_POS, ending_position_ALT from groc_svs_summary where WLI='1'")
    groc_fetch_data = cur.fetchall()

    pos = 2
    for var in groc_fetch_data:
        source_list = list(var[1:3])
        target_list = list(var[0:3])
        for i in range(len(source_list)):
            target_list.insert(i + pos, source_list[i])
            data.append(target_list)

    cur.close()

    # cur = mysql.connection.cursor()
    # cur.execute("select starting_position, ending_position, starting_position from wli_dels_longranger_chr12")
    # wli_dels_fetch_data = cur.fetchall()
    #
    # pos = 2
    # for var in wli_dels_fetch_data:
    #     source_list = list(var[1:3])
    #     target_list = list(var[0:3])
    #     for i in range(len(source_list)):
    #         target_list.insert(i + pos, source_list[i])
    #         data.append(target_list)
    #
    # cur.close()
    print("gwlidelgwlidelgwlidelgwlidelgwlidelgwlidelgwlidelgwlidel", data)
    return render_template('gwlidel.html', title='HRDP', data=data)

@visuals.route('/wli/large')
def gwlilarge():
    data = []

    # cur = mysql.connection.cursor()
    # cur.execute("select * from sv_research_test_schema.groc_chr12")
    # groc_fetch_data = cur.fetchall()
    #
    # pos = 2
    # for var in groc_fetch_data:
    #     source_list = list(var[1:3])
    #     target_list = list(var[0:3])
    #     for i in range(len(source_list)):
    #         target_list.insert(i + pos, source_list[i])
    #         data.append(target_list)
    #
    # cur.close()

    cur = mysql.connection.cursor()
    cur.execute(
        "select cast(substring_index(a.CHROM, 'chr', -1) as unsigned) as chr, CASE WHEN ALT LIKE '\<%' THEN CAST(substring_index(substring_index(a.INFO, ';', 1), '=', -1) AS unsigned) ELSE CAST(substring_index(substring_index(substring_index(ALT, ':', -1), '[', 1), ']', 1) AS unsigned) END AS END, POS from tsv_wli_dels_longranger a where cast(substring_index(a.CHROM, 'chr', -1) as unsigned) != 0 order by chr")
    wli_dels_fetch_data = cur.fetchall()

    pos = 2
    for var in wli_dels_fetch_data:
        source_list = list(var[1:3])
        target_list = list(var[0:3])
        for i in range(len(source_list)):
            target_list.insert(i + pos, source_list[i])
            data.append(target_list)

    cur.close()

    print("wlilongrangerwlilongrangerwlilongrangerwlilongrangerwlilongrangerwlilongrangerwlilongrangerwlilongranger", data)

    return render_template('gwlilarge.html', title='HRDP', data=data)

@visuals.route('/wmi/dels')
def gwmidel():
    data = []

    cur = mysql.connection.cursor()
    cur.execute("select CONCAT(\"GGG_\", CHROM), starting_position_POS, ending_position_ALT from groc_svs_summary where WMI='1'")
    groc_fetch_data = cur.fetchall()

    pos = 2
    for var in groc_fetch_data:
        source_list = list(var[1:3])
        target_list = list(var[0:3])
        for i in range(len(source_list)):
            target_list.insert(i + pos, source_list[i])
            data.append(target_list)

    cur.close()

    # cur = mysql.connection.cursor()
    # cur.execute("select cast(substring_index(a.CHROM, 'chr', -1) as unsigned) as chr, CASE WHEN ALT LIKE '\<%' THEN CAST(substring_index(substring_index(a.INFO, ';', 1), '=', -1) AS unsigned) ELSE CAST(substring_index(substring_index(substring_index(ALT, ':', -1), '[', 1), ']', 1) AS unsigned) END AS END, POS from tsv_wmi_dels_longranger a where cast(substring_index(a.CHROM, 'chr', -1) as unsigned) != 0 order by chr")
    # wmi_dels_fetch_data = cur.fetchall()
    #
    #
    # pos = 2
    # for var in wmi_dels_fetch_data:
    #     source_list = list(var[1:3])
    #     target_list = list(var[0:3])
    #     for i in range(len(source_list)):
    #         target_list.insert(i + pos, source_list[i])
    #         data.append(target_list)
    #
    # # print(data)
    # cur.close()

    print("gwmidelgwmidelgwmidelgwmidelgwmidelgwmidelgwmidelgwmidelgwmidelgwmidelgwmidelgwmidelgwmidelgwmidel", data)


    return render_template('gwmidel.html', title='HRDP', data=data)

@visuals.route('/wmi/large')
def gwmilarge():
    data = []

    cur = mysql.connection.cursor()
    cur.execute("select cast(substring_index(a.CHROM, 'chr', -1) as unsigned) as chr, CASE WHEN ALT LIKE '\<%' THEN CAST(substring_index(substring_index(a.INFO, ';', 1), '=', -1) AS unsigned) ELSE CAST(substring_index(substring_index(substring_index(ALT, ':', -1), '[', 1), ']', 1) AS unsigned) END AS END, POS from tsv_wmi_dels_longranger a where cast(substring_index(a.CHROM, 'chr', -1) as unsigned) != 0 order by chr")
    groc_fetch_data = cur.fetchall()

    pos = 2
    for var in groc_fetch_data:
        source_list = list(var[1:3])
        target_list = list(var[0:3])
        for i in range(len(source_list)):
            target_list.insert(i + pos, source_list[i])
            data.append(target_list)

    cur.close()
    print("wmilongrangerwmilongrangerwmilongrangerwmilongrangerwmilongrangerwmilongrangerwmilongrangerwmilongrangerwmilongranger", data)
    # cur = mysql.connection.cursor()
    # cur.execute("select a.CHROM, CASE WHEN ALT LIKE '\<%' THEN substring_index(substring_index(a.INFO, ';', 1), '=', -1) ELSE substring_index(substring_index(substring_index(ALT, ':', -1), '[', 1), ']', 1) END AS END, POS from tsv_wli_dels_longranger a")
    # wli_dels_fetch_data = cur.fetchall()
    #
    # pos = 2
    # for var in wli_dels_fetch_data:
    #     source_list = list(var[1:3])
    #     target_list = list(var[0:3])
    #     for i in range(len(source_list)):
    #         target_list.insert(i + pos, source_list[i])
    #         data.append(target_list)
    #
    # cur.close()
    # print("<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>", data)

    return render_template('gwmilarge.html', title='HRDP', data=data)

@visuals.route('/geoChart/large')
def geoChart():
    data = [
        ['City', 'Population', 'Area'],
        ['Rome', 2761477, 1285.31],
        ['Milan', 1324110, 181.76],
        ['Naples', 959574, 117.27],
        ['Turin', 907563, 130.17],
        ['Palermo', 655875, 158.9],
        ['Genoa', 607906, 243.60],
        ['Bologna', 380181, 140.7],
        ['Florence', 371282, 102.41],
        ['Fiumicino', 67370, 213.44],
        ['Anzio', 52192, 43.43],
        ['Ciampino', 38262, 11]
    ]
    return render_template('geochart.html', title='HRDP', data=data)

app/templates/data_hrdp.html
{% extends "layout.html" %}
{% block content %}
{% macro grid(tab=tab) -%}
<table class="table table-striped table-sm table-hover">
  <thead>
    <tr>
    {% for column in columnset[tab] %}
        <th scope="col">{{column}}</th>
    {% endfor %}
    </tr>
  </thead>
  <tbody>
    {% for table in tableset[tab] %}
    <tr>
        {% for column in columnset[tab] %}
        <td>{{ table[column] }}</td>
        {% endfor %}
    </tr>
    {% endfor %}
  </tbody>
</table>
{%- endmacro %}
<!-- Nav tabs -->
<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="strain-tab" data-toggle="tab" href="#strain" role="tab" aria-controls="strain" aria-selected="false">Strain</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="animal-tab" data-toggle="tab" href="#animal" role="tab" aria-controls="animal" aria-selected="false">Animal</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="tissue-tab" data-toggle="tab" href="#tissue" role="tab" aria-controls="tissue" aria-selected="false">Tissue</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="sequencing-tab" data-toggle="tab" href="#sequencing" role="tab" aria-controls="sequencing" aria-selected="false">Sequencing</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="analysis-tab" data-toggle="tab" href="#analysis" role="tab" aria-controls="analysis" aria-selected="false">Analysis</a>
    </li>
</ul>
<!-- Tab panes -->
<div class="tab-content">
    <div class="tab-pane fade show active" id="strain" role="tabpanel" aria-labelledby="strain-tab">{{ grid('strain')}}</div>
    <div class="tab-pane fade" id="animal" role="tabpanel" aria-labelledby="animal-tab">{{ grid('animal')}}</div>
    <div class="tab-pane fade" id="tissue" role="tabpanel" aria-labelledby="tissue-tab">{{ grid('tissue')}}</div>
    <div class="tab-pane fade" id="sequencing" role="tabpanel" aria-labelledby="sequencing-tab">{{ grid('sequencing')}}</div>
    <div class="tab-pane fade" id="analysis" role="tabpanel" aria-labelledby="analysis-tab">{{ grid('analysis')}}</div>
</div>
{% endblock content %}

app/templates/geochart.html
{% extends "layout.html" %}
{% block content %}
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type='text/javascript'>
     google.charts.load('current', {
       'packages': ['geochart'],
       // Note: you will need to get a mapsApiKey for your project.
       // See: https://developers.google.com/chart/interactive/docs/basic_load_libs#load-settings
       'mapsApiKey': 'AIzaSyDoh8UpZM-l5I1jjE12Rosix8YKQcXbc9A'
     });
     google.charts.setOnLoadCallback(drawMarkersMap);

      function drawMarkersMap() {
          let data = google.visualization.arrayToDataTable({{data | safe}});
          let options = {
            region: 'IT',
            displayMode: 'markers',
            colorAxis: {colors: ['green', 'blue']}
          };

          let chart = new google.visualization.GeoChart(document.getElementById('chart_div'));
          chart.draw(data, options);
       }
</script>
<h1>World Chart</h1>
<div id="chart_div" style="width: 900px; height: 800px;"></div>
{% endblock content %}

app/templates/gwlidel.html
{% extends "layout.html" %}
{% block content %}
<script type="text/javascript">

        let newID = [];
        function tabIdChanger(){
            let elms = document.querySelectorAll("[id='chart_div']");

            for(let i = 0; i < elms.length; i++){
                elms[i].id = 'chart_div' + i;
                newID.push(elms[i].id)
                console.log(elms[i].id)
            }
        }

      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);


      function drawChart() {
        let data = google.visualization.arrayToDataTable({{data | safe}}, true);

        let options = {
          legend: 'none',
          bar: { groupWidth: '100%' }, // Remove space between bars.
          candlestick: {
            fallingColor: { strokeWidth: 0, fill: '#a52714' }, // red
            risingColor: { strokeWidth: 0, fill: '#0f9d58' }   // green
          },
          axisTitlesPosition: ''
        };

        tabIdChanger();

        for(let i = 0; i < newID.length; i++){
            console.log(newID[i])
            let chart = new google.visualization.CandlestickChart(document.getElementById(newID[i]));
            chart.draw(data, options);
        }
        // chart.draw(data, options);
      }
</script>
<h1>GROC-WLI Dels</h1>
<div id="chart_div" style="width: 900px; height: 800px;"></div>
{% endblock content %}

app/templates/gwlilarge.html
{% extends "layout.html" %}
{% block content %}
<script type="text/javascript">

        let newID = [];
        function tabIdChanger(){
            let elms = document.querySelectorAll("[id='chart_div']");

            for(let i = 0; i < elms.length; i++){
                elms[i].id = 'chart_div' + i;
                newID.push(elms[i].id)
                console.log(elms[i].id)
            }
        }

      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);


      function drawChart() {
          console.log("draw")
        let data = google.visualization.arrayToDataTable({{data | safe}}, true);

        let options = {
          legend: 'none',
          bar: { groupWidth: '100%' }, // Remove space between bars.
          candlestick: {
            fallingColor: { strokeWidth: 0, fill: '#a52714' }, // red
            risingColor: { strokeWidth: 0, fill: '#0f9d58' }   // green
          },
          axisTitlesPosition: ''
        };

        tabIdChanger();

        for(let i = 0; i < newID.length; i++){
            console.log(newID[i])
            let chart = new google.visualization.CandlestickChart(document.getElementById(newID[i]));
            chart.draw(data, options);
        }
        // chart.draw(data, options);
      }
</script>
<h1>GROC-WLI Large SVs</h1>
<div id="chart_div" style="width: 900px; height: 800px;"></div>
{% endblock content %}

app/templates/gwmidel.html
{% extends "layout.html" %}
{% block content %}
<script type="text/javascript">

        let newID = [];
        function tabIdChanger(){
            let elms = document.querySelectorAll("[id='chart_div']");

            for(let i = 0; i < elms.length; i++){
                elms[i].id = 'chart_div' + i;
                newID.push(elms[i].id)
                console.log(elms[i].id)
            }
        }

      google.charts.load('current', {'packages':['corechart']});
      google.charts.setOnLoadCallback(drawChart);


      function drawChart() {
          console.log("draw")
        let data = google.visualization.arrayToDataTable({{data | safe}}, true);

        let options = {
          legend: 'none',
          bar: { groupWidth: '100%' }, // Remove space between bars.
          candlestick: {
            fallingColor: { strokeWidth: 0, fill: '#a52714' }, // red
            risingColor: { strokeWidth: 0, fill: '#0f9d58' }   // green
          },
          axisTitlesPosition: ''
        };

        tabIdChanger();

        for(let i = 0; i < newID.length; i++){
            console.log(newID[i])
            let chart = new google.visualization.CandlestickChart(document.getElementById(newID[i]));
            chart.draw(data, options);
        }
        // chart.draw(data, options);
      }
</script>
<h1>GROC-WMI Dels</h1>
<div id="chart_div" style="width: 900px; height: 800px;"></div>
{% endblock content %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- favicon -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    <!-- google visualization -->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <meta charset="UTF-8">
    {% if title %}
        <title>Flask - {{ title }}</title>
    {% else %}
        <title>Flask</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4">HRDP Project</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                        <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                        <a class="nav-item nav-link" href="{{ url_for('data.data_hrdp') }}">Data</a>
                        <a class="nav-item nav-link" href="{{ url_for('visuals.gwlidel') }}">WLI-Dels</a>
                        <a class="nav-item nav-link" href="{{ url_for('visuals.gwlilarge') }}">WLI-Large</a>
                        <a class="nav-item nav-link" href="{{ url_for('visuals.gwmidel') }}">WMI-Dels</a>
                        <a class="nav-item nav-link" href="{{ url_for('visuals.gwmilarge') }}">WMI-Large</a>
                        <a class="nav-item nav-link" href="{{ url_for('visuals.geoChart') }}">World-Report</a>
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if current_user.is_authenticated %}
                            <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                            <a class="nav-item nav-link" href="{{ url_for('posts.creating_post') }}">Post</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                        {% else %}
                            <a class="nav-item nav-link" href="{{ url_for('users.login_plain') }}">Login</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                {% block content %}{% endblock %}
            </div>
            <!--<div class="col-md-4">
                <div class="content-section">
                    <h3>Chen's lab News</h3>
                    <p class='text-muted'>You can put any information here you'd like.
                        <ul class="list-group">
                            <li class="list-group-item list-group-item-light">Latest Posts</li>
                            <li class="list-group-item list-group-item-light">Announcements</li>
                            <li class="list-group-item list-group-item-light">Calendars</li>
                            <li class="list-group-item list-group-item-light">etc</li>
                        </ul>
                    </p>
                </div>
            </div> -->
        </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

app/templates/view.html
{% extends "layout.html" %}
{% block content %}
<h3>Available Data</h3>
<table class="table table-striped table-sm">
  <thead>
    <tr>
    {% for column in columnset %}
        <th scope="col">{{column}}</th>
    {% endfor %}
    </tr>
  </thead>
  <tbody>
    {% for row in tableset %}
    <tr>
        <td><a href="{{url_for('data.view_detail', run_id=row[0])}}">{{row[0]}}</a></td>
        {% for i in range(1, row| length)%}
        <td>{{ row[i] }}</td>
        {% endfor %}
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

app/templates/view_detail.html
{% extends "layout.html" %}
{% block content %}
<h3> Detailed view of {{detail_target}} </h3> 
{% macro grid(table=table) -%}
<table class="table table-sm table-striped">
    {% for column in columnset[table] %}
      <tr>
      {% set class = tableset[table] %}
        <th scope="row">{{column}}</th>

        {% if table == 'Analysis' %}
          {% set classlist = tableset[table] %}
          {% for class in classlist %}
              <td>{{ class[column] }}</td>
          {% endfor %}

        {%elif table == 'Deepvariant results'%}
          {% set classlist = tableset[table] %}
          {% for class1 in classlist %}
              <td>{{ class1[column] }}</td>
          {% endfor %}

        {% else %}
              <td>{{ class[column] }}</td>
        {% endif %}
      </tr>
    {% endfor %}
</table>
{%- endmacro %}
{% macro detail(table=table) -%}
{%- endmacro %}


{% for name in column_list %}
  <h4>{{name}}</h4>
  {{grid(name)}}
{%endfor%}
{% endblock content %}